highlighter: rouge
themeColor: #7cbaff

title: BUGS NYU
email:
description: ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins: [jekyll-paginate]

paginate: 6
paginate_path: "/news/page:num/"

collections:
  events:
    output: true
    permalink: /calendar/:path/
  projects:
    output: true
    permalink: /projects/:path/
  contributors:
    output: true
    permalink: /about/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
# - scope:
#     path: ""
#     type: "posts"
#   values:
#     layout: "post"


# Build settings
markdown: kramdown
