title: BUGS - NYU
email: bugscommunicationsteam@gmail.com
description: >-
  NYU BUGS is the open source club at NYU. We promote open source by engaging students
  through collaborative projects, hosting industry professions, and running open
  source workshops.
url: "https://bugs-nyu.github.io"
repository_url: https://github.com/BUGS-NYU/bugs-nyu.github.io
org_url: https://github.com/BUGS-NYU/
markdown: kramdown

# Edit this if you'd like to check out the site on your own fork
baseurl: "/bugs-nyu.github.io" # the subpath of your site, e.g. /blog

future: true

# -- Collection settings --
collections: # ~ sign in yaml means null
  events: ~
  contributors: ~

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "base"
